line_width = 2;
enable_markers = 0;

line_styles = {'-', '-', '-', '-', '-', '-', '-', '-', '-', '-'};
markers = {'o', '+', '*', 'x', 'p', 'd', 'o','+', '*', 'x'};

'p2s 617 summary bar';
% line_cols = {
% 	'red',...
% 	'blue',...
% 	'forest_green',...
% 	'magenta',...
% 	'dark_orange',...
% 	'dark_slate_gray',...
% 	};

'p2s 617 summary bar ppt';
% line_cols = {
% 	'blue',...
% 	'forest_green',...
% 	'magenta',...
% 	'dark_orange',...
% 	'dark_slate_gray',...
% 	};

'p2s 617 ablation line';
% line_cols = {
% 	'red',...
% 	'blue',...
% 	'forest_green',...
% 	'magenta',...
% 	'dark_orange',...
% 	};
% line_styles = {'--', '-', '-', '-', '-', '-', '-', '-', '-', '-'};

'p2s ipsc seg bar';
bar_plot = 1;
bar_vals = 1;
bar_vals_font_size = 12;

enable_y_label = 1;
enable_x_label = 0;
vertcal_x_label = 0;
colored_x_label = 0;
add_ylabel_to_title = 0;

axes_font_size = 20;
legend_font_size = 16;
title_font_size = 20;

y_limits = [0, 95];

'ipsc_seg';
% line_cols = {
% 'forest_green',...
% 'dark_orange',...
% 'purple',...
% };

'vid_arch';
% bar_vals = 1;

% line_cols = {
% 	'red',...
% 	'blue',...
% 	'forest_green',...
% 	'magenta',...
% 	'dark_orange',...
% 	};

'static-vid red-blue';
% line_cols = {
% 	'magenta',...
% 	'light_blue',...
% 	'red',...
% 	'blue',...
% 	'maroon',...
% 	'midnight_blue',...
% 	};

'static-vid red-green';
% line_cols = {
% 	'red',...
% 	'lime',...
% 	'dark_red',...
% 	'green',...
% 	'maroon',...
% 	'forest_green',...
% 	};

'static-vid red-green N-wise groups';
% line_cols = {
% 	'red',...
% 	'dark_lime',...
% 	'dark_red',...
% 	'dark_green',...
% };

'static-vid red-green T-wise groups 4-way';
% line_cols = {
% 	'red_255',...
% 	'green_255',...
% 	'red_192',...
% 	'green_192',...
% 	'red_128',...
% 	'green_128',...
% 	'red_64',...
% 	'green_64',...
% };

'static-vid red-green T-wise groups 5-way';
% line_cols = {
% 	'red_255',...
% 	'green_255',...
% 	'red_207',...
% 	'green_207',...
% 	'red_159',...
% 	'green_159',...
% 	'red_111',...
% 	'green_111',...
% 	'red_64',...
% 	'green_64',...
% };


'seg fbb';
% line_cols = {
% 	'red_255',...
% 	'green_255',...
% 	'red_176',...
% 	'green_176',...
% 	'red_96',...
% 	'green_96',...
% };


'cls_eq';
% line_cols = {
% 	'red',...
% 	'forest_green',...
% };

'batch';
% line_cols = {
% 	'blue',...
% 	'dark_orange',...
% };

'p2s acamp';
% line_cols = {
% 	'red',...
% 	'blue',...
% 	'cyan',...
% 	'magenta',...
% 	'lime',...
% 	'forest_green',...
% 	'purple',...
% 	'dark_orange',...
% 	'maroon',...
% 	'dark_slate_gray',...
% 	  };

% line_cols = {
% 	'magenta',...
% 	'lime',...
% 	'cyan',...
% 	'forest_green',...
% 	'blue',...
% 	'red',...
% 	'purple',...
% 	'dark_orange',...
% 	'maroon',...
% 	'dark_slate_gray',...
% 	  };

'p2s acamp paper';
line_cols = {
	'red_255',...
	'green_255',...
	'red_111',...
	'green_111',...
	};

'vid len detrac';
% line_cols = {
% 	'red',...
% 	'blue',...
% 	'cyan',...
% 	'magenta',...
% 	'forest_green',...
% 	'dark_orange',...
% 	};

'vid len ipsc';
% line_cols = {
% 	'red',...
% 	'blue',...
% 	'cyan',...
% 	'lime',...
% 	'magenta',...
% 	};

'1d late';
% line_cols = {
% 	'red_255',...
% 	'green_255',...
% 	'red_176',...
% 	'green_176',...
% 	'green_96',...
% };

'p2s ipsc cls';
% line_cols = {
% 'magenta',...
% 'green',...
% 'cyan',...
% 'forest_green',...
% 'blue',...
% 'red',...
% 'purple',...
% 'dark_orange',...
% 'maroon',...
% 'dark_slate_gray',...
% };	  

'p2s ipsc det';
% line_cols = {
% 'forest_green',...
% 'blue',...
% 'red',...
% 'purple',...
% 'dark_orange',...
% 'maroon',...
% 'dark_slate_gray',...
% };	  


% line_cols = {
% 	'red_1', 'red_2', 'red_3', 'red_4', 'red_5'
% 	};


% line_styles = {':', ':', ':', '-', '-', '-', '-', '-', '-', '-', '-', '-'};
% line_styles = {'-.', '-.', '-.', '-', '-', '-', '-', '-', '-', '-', '-', '-'};
% line_styles = {'--', '--', '--', '-', '-', '-', '-', '-', '-', '-', '-', '-'};
% line_styles = {'-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-'};
% markers = {'o', '+', '*', 'x', 'p', 'd', 'o','+', '*', 'x'};


mode = 0;
if mode == 1
%     line_cols = {'blue', 'forest_green', 'blue', 'forest_green'};
    line_cols = {'blue', 'purple', 'blue', 'purple'};
    line_styles = {'-', '-', '-', ':', ':', ':'};
    markers = {'o', '+','o', '+'};
    % valid_columns = [1, 3];
elseif mode == 2
    line_cols = {'blue', 'purple', 'blue', 'purple'};
    line_styles = {'-', '-', ':', ':', ':'};
    markers = {'o', '+', 'o', '+'};
elseif mode == 3
%         line_cols = {'blue', 'blue', 'forest_green', 'forest_green',...
%             'magenta', 'magenta', 'red', 'red',...
%             'cyan', 'cyan', 'purple', 'purple'};
        
%         line_cols = {'blue', 'red', 'forest_green', 'cyan','purple','green',...
%             'blue', 'forest_green', 'green','red', 'cyan','purple'};
        
        line_cols = {'blue', 'blue', 'blue',...
            'red','red','red',...
            'forest_green',...
            'forest_green', 'forest_green',...
            'purple', 'purple','purple'};
        
        
        line_styles = {
            '-', '-', '-', '-',...
            '-', '-', '-', '-',...
            '-', '-','-', '-'...
            '-', '-', '-', '-'};
        markers = {
            'o', 'o','o', 'o',...
            'o', 'o','o', 'o',...
            'o', 'o','o', 'o',...
            'o', 'o','o', 'o',...
            };
        
elseif mode == 4
%         line_cols = {'blue', 'blue', 'forest_green', 'forest_green',...
%             'magenta', 'magenta', 'red', 'red',...
%             'cyan', 'cyan', 'purple', 'purple'};
        
%         line_cols = {'blue', 'red', 'forest_green', 'cyan','purple','green',...
%             'blue', 'forest_green', 'green','red', 'cyan','purple'};
        
        line_cols = {'blue', 'blue', 'blue', 'blue',...
            'red','red','red','red',...
            'forest_green',...
            'forest_green', 'forest_green', 'forest_green',...
            'purple', 'purple','purple','purple'};
        
        
        line_styles = {
            '-', '-', '-', '-',...
            '-', '-', '-', '-',...
            '-', '-','-', '-'...
            '-', '-', '-', '-'};
        markers = {
            'o', 'o','o', 'o',...
            'o', 'o','o', 'o',...
            'o', 'o','o', 'o',...
            'o', 'o','o', 'o',...
            };
end
% line_styles = {'-', '-', '-', '--', '--', '--'};

% line_styles = {'--', '-', '-', '-', '-'};
% line_styles = {'-', ':', '-', ':', '-', ':', '-', ':', '-', ':', '-', ':', '-', ':', '-', ':', '-', ':'};
% line_styles = {'-', '--', '-', '--', ':', '-', '--', '-', '--', '-', '--', '-', '--', '-', '--', '-', '--', '-', '--'};

% line_styles = {'-', '-', '--', '--', '--'};
% line_styles = {'-', '-', '--', '-'};

% line_styles = {'-o', '-+', '-*', '-x', '-s', '-p'};


% line_specs = {'-og', '-+r'};
% line_specs = {'--or', '-+g', '--xm', '-xm'};

% line_specs = {'-or', '-+g', '-*b', '--xm'};

% line_specs = {'-or', ':+r', '-*b', ':xb'};
% line_specs = {'-or', '--+r', '-*b', '--xb'};

% line_specs = {'-or', '-+g', '--*b', '--xm'};
% line_specs = {'--or', '-+b', '-*g', '-xm'};

% line_specs = {'--or', '-+g', '-*b', '-xm', '-sc', '-pk'};

% line_specs = {'-or', '-+g', '-*b',...
%     '--or', '--+g', '--*b'};

% line_specs = {'-+g', '-*b', '-xm',...
%     '--+g', '--*b', '--xm'};

% line_specs = {'-or', '-+g', '-*b', '-xm',...
%     '--or', '--+g', '--*b', '--xm'};

% line_specs = {'-or', '-+g', '-*b', '-xm', '-sc',...
%     '--or', '--+g', '--*b', '--xm', '--sc'};

% line_specs = {'-or', '--*r', '-+g', '--xg'};
% line_specs = {'-or', '-+g', '--*r', '-+g', '--xg'};

line_cols_all = {
	'magenta', 'green', 'cyan', 'forest_green','blue', 'red', 'purple', 'dark_orange',...
	'peach_puff', 'maroon', 'white'
	};

line_cols = [line_cols, line_cols_all];


% set(0,'DefaultAxesFontName', 'Times New Roman');
% k=importdata('radon.txt');

% plot_title_override='UNet';
% k=importdata('unet_summary.txt');

% plot_title_override='SegNet';
% k=importdata('segnet_summary.txt');

% plot_title_override='Deeplab';
% k=importdata('deeplab_summary.txt');

% plot_title_override='DenseNet';
% k=importdata('densenet_summary.txt');

% plot_title_override='Comparing models';
% plot_title_override='Selective Training';

% plot_title_override='Recall rates using 5000 video images for training';
% plot_title_override='Recall rates on 20K 3-class test set without static images';

% y_label_override = 'Recall (%)';
% y_label_override = 'pixel accuracy';
% y_label_override = 'acc/IOU';
% y_label_override = 'Recall / Precision (%)';